### ISSUE TITLE
Menambah Tautan Demo Aplikasi

### ISSUE THREAD

**Issue by jefrydco** [MuhamadAhmadin/code-roar#1]
Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Ahmadin. Mas juga sudah menambahkan beberapa gaya sendiri. Keren Mas!

Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan, yakni

Menambahkan tautan ke demo aplikasi. Untuk yang menambahkan tautan ke demo aplikasi, kalau ngga salah bisa melalui bagian yang ada di sini Mas

![Vue.js Intermediate - jefrydco](https://user-images.githubusercontent.com/20434351/96429667-673ee180-122b-11eb-957f-d26e39401f68.png)

Tautan ke demo aplikasi akan sangat berguna bagi teman-teman yang ingin melihat hasil proyek Mas ini tanpa harus menjalankannya di lokal.

Semangat selalu ya! :muscle:

**Comment by MuhamadAhmadin** [comment]
[image: about webinar pens.jpg]

Terimakasih atas koreksinya mas Jefry Dewangga, saya sudah memperbaiki
kekurangan di repositori saya mas. terimakasih

**Comment by jefrydco** [comment]
Terima kasih kembali Mas, kalau begitu saya tutup ya _issue_-nya. Semangat selalu! :muscle:
